[package]
name = "sgb_unlimiter"
version = "0.1.0"
edition = "2021"
authors = [
  "ParkSnoopy <sunwoo2539@gmail.com>",
  "mil-acc-github <milacc0000@gmail.com>"
]
license = "GPL-3.0-or-later"


[profile.release]
strip = true
lto   = true


[dependencies]
colored = "2.1.0"
psutil = "3.2.2"
