[package]
name = "sgb_unlimiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
colored = "2.1.0"
console = "0.15.8"
deelevate = "0.2.0"
privilege_level = "0.1.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["impl-default", "debug", "winuser", "wingdi", "winnt", "processthreadsapi", "handleapi", "tlhelp32"] }

[build-dependencies]
static_vcruntime = "2.0.0"
winres = "0.1.12"
